# Generated by Django 3.0.7 on 2020-07-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_auto_20200708_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'admin'), (1, 'User')], default=1),
        ),
    ]
