# Generated by Django 3.0.7 on 2020-07-08 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_auto_20200708_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic_path', models.CharField(max_length=511)),
                ('workplace', models.CharField(max_length=255)),
                ('paper', models.CharField(max_length=255)),
                ('cv_path', models.CharField(blank=True, default='', max_length=511)),
                ('desc', models.CharField(max_length=65535)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='cv_path',
            field=models.CharField(blank=True, default='', max_length=511),
        ),
        migrations.AddField(
            model_name='teacher',
            name='desc',
            field=models.CharField(default=1, max_length=65535),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='pic_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=511),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='registered_for_presentations',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=65535)),
                ('teachers', models.ManyToManyField(to='backend_api.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=65535)),
                ('presenters', models.ManyToManyField(to='backend_api.Presenter')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='registered_workshops',
            field=models.ManyToManyField(blank=True, to='backend_api.Workshop'),
        ),
    ]
