# Generated by Django 3.0.7 on 2020-07-08 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_auto_20200708_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenter',
            name='pic_path',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='pic_path',
        ),
        migrations.AddField(
            model_name='presenter',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
