# Generated by Django 3.0.7 on 2020-07-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_misc_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misc',
            name='description',
        ),
    ]
