# Generated by Django 3.0.7 on 2020-07-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_remove_misc_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc',
            name='description',
            field=models.CharField(blank=True, max_length=65535),
        ),
    ]
