# Generated by Django 3.0.7 on 2020-07-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_auto_20200717_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misc',
            old_name='description',
            new_name='desc',
        ),
    ]
