# Generated by Django 3.0.7 on 2020-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0017_auto_20200717_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('target_mode', models.PositiveSmallIntegerField(choices=[(2, 'Send email to selected workshop(s) registered users'), (3, 'Send email to presentations users'), (1, 'Send email to all users'), (4, 'Send email to custom selection of users')], default=1)),
                ('HTML_body', models.CharField(max_length=65535)),
                ('user_selection', models.ManyToManyField(blank=True, to='backend_api.User')),
                ('workshop_selection', models.ManyToManyField(blank=True, to='backend_api.Workshop')),
            ],
        ),
    ]
