# Generated by Django 3.0.7 on 2020-07-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_mailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('authority', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_price', models.PositiveIntegerField()),
                ('presentation', models.BooleanField(blank=True, default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('ref_id', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.User')),
                ('workshops', models.ManyToManyField(blank=True, to='backend_api.Workshop')),
            ],
        ),
    ]
