# Generated by Django 3.0.7 on 2020-07-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0020_auto_20200720_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
