# Generated by Django 3.0.7 on 2020-07-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0022_auto_20200724_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'NOT_ASSIGNED'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Advanced')], default=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='has_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'NOT_ASSIGNED'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Advanced')], default=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='prerequisites',
            field=models.CharField(default='', max_length=65535),
        ),
    ]
