# Generated by Django 3.0.7 on 2020-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0023_auto_20200724_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
