# Generated by Django 3.0.7 on 2020-07-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0024_presentation_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='capacity',
        ),
        migrations.AddField(
            model_name='workshop',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
