# Generated by Django 3.0.7 on 2020-07-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0025_auto_20200724_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='prerequisites',
            field=models.CharField(blank=True, default='', max_length=65535),
        ),
    ]
