# Generated by Django 3.0.7 on 2020-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0028_auto_20200725_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
