# Generated by Django 3.0.7 on 2020-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0030_remove_user_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='add_to_calendar_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
